# Bundler aliases
alias b 'bi'
alias ba 'bundle add'
alias bc 'bundle console'
alias bck 'bundle check'
alias bcn 'bundle clean'
alias be 'bundle exec'
alias bi 'bundle install'
alias bl 'bundle list'
alias bo 'EDITOR=nova bundle open'
alias bout 'bundle outdated'
alias bp 'bundle package'
alias bu 'bundle update'
alias bx 'bundle exec'
alias tb 't b'
alias tbu 't bu'
alias tbx 't bx'

# Docker aliases
alias dc 'docker-compose'
alias dcx 'dc exec web'

# Additional git aliases
alias ghe 'git rev-parse HEAD'
alias gpo 'git push origin --set-upstream (__git.current_branch)'
alias grbm 'git rebase (__git.default_branch)'
alias gs 'git status'
alias pop 'git stash pop'
alias stash 'git stash'
alias cherry 'git_cherry'
alias rebase 'git_rebase'
alias gsync 'git_pull'
alias pull 'git_pull'

# GitHub CLI
alias ghpr 'gh pr create --web'

# Editor aliases
alias m 'mate -w .'
alias n 'nova .'

# Development aliases
alias bullet 'set -lx BULLET 1'
alias ci 'bin/rails ci'
alias derp 'set -lx RUBYOPT W0'
alias dotfiles 'cd ~/.dotfiles'
alias jitless 'set -lx JRUBY_OPTS "$JRUBY_OPTS -J-Djruby.compile.mode=OFF"'
alias jrbdev 'set -lx JRUBY_OPTS "$JRUBY_OPTS --dev --disable:did_you_mean --debug"'
alias sp 'spec'
alias spf 'specf'
alias spm 'specm'
alias spec 't rspec'
alias specf 'spec --only-failures'
alias specm 'spec (git ls-files --modified spec)'
alias std 'standardize'
alias std! 'standardize!'
alias standardize 'bin/standardrb --fix'
alias standardize! 'bin/standardrb --fix-unsafely'
alias t 'turbo'
alias turbo 'derp jrbdev'

# Misc aliases
alias cd.. 'cd ..'
alias cloud 'cd ~/Library/Mobile\ Documents/com~apple~CloudDocs'
alias dotfiles 'cd ~/.dotfiles'
alias http 'python -m SimpleHTTPServer'
alias kp 'ps auxwww'
alias l 'ls -lA'
alias ll 'ls -lAh'
alias lll 'ls -lah'
alias ls 'ls -AG'
alias md 'mkdir -p'
alias rd 'rmdir'
alias ns 'nslookup'
alias o 'open .'
alias path 'echo $PATH'
alias redis 'redis-server $HOMEBREW_REPOSITORY/etc/redis.conf'
alias reload 'source ~/.config/fish/config.fish'
alias restart 'exec fish'
