#!/usr/bin/env ruby
# vim:ft=ruby:

# Original: http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen
git_bundles = [
  "git://github.com/jdevera/vim-protobuf-syntax.git",
  "git://github.com/mileszs/ack.vim.git",
  "git://github.com/tpope/vim-endwise.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-surround.git"
]

vim_org_scripts = [
  ["vibrantink", "10117", "colors"]
]

get_requests = []

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

trash = ARGV.include?('--trash')

if trash
  puts "Trashing everything (lookout!)"
  Dir["*"].each {|d| FileUtils.rm_rf d }
end

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  if !trash && File.exists?(dir)
    puts " Skipping #{dir}"
    next
  end
  puts " Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  local_file = File.join(name, script_type, "#{name}.#{script_type == 'zip' ? 'zip' : 'vim'}")
  if !trash && File.exists?(local_file)
    puts " Skipping #{local_file}"
    next
  end
  puts " Downloading #{name}"
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
  if script_type == 'zip'
    %x(unzip -d #{name} #{local_file})
  end
end

get_requests.each do |name, script_url, script_type|
  local_file = File.join(name, script_type, "#{name}.vim")
  if !trash && File.exists?(local_file)
    puts " Skipping #{local_file}"
    next
  end

  puts " Downloading #{name}"
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open(script_url).read
  end
end
